name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download FluffyChat
        run: git clone https://gitlab.com/famedly/fluffychat
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build with Flutter
        working-directory: ./fluffychat
        run: flutter build windows --release
      
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: All
          path: ./fluffychat/*
